project:
  type: book

book:
  title: "IDR4000 Mappeeksamen"
  author: "404"
  date: "11/17/2023"
  chapters:
    - index.qmd
    - Del_1_Reabilitet.qmd
    - Del_2_Labrapport.qmd
    - Del_3_Vitenskapsfilosofi.qmd
    - Del_4.qmd
    - Del_5_Analysere gjentatte tiltak eksperimenter.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: darkly
  pdf:
    documentclass: scrreprt

editor: visual

